language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test

deploy:
  - provider: npm
    email: ${NPM_USER_EMAIL}
    api_key: ${NPM_USER_API_KEY}
    on:
      tags: true
      repo: eshepelyuk/asciidoctor-plantuml.js
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    on:
      tags: true
      repo: eshepelyuk/asciidoctor-plantuml.js
